### ISSUE TITLE
Add additional weapon attachments to VWLE

### ISSUE THREAD

**Issue by AJCStriker** [1st-rapid-response-force/1rrf_framework.Stratis#7]

**Comment by AJCStriker** [comment]
In particular
- Primary Optics
- Primary Suppresor
- Primary IR / Light
- Primary Bipod
- Secondary Suppresor

PLEASE REMOVE:
- Launcher Attachments - Because WTF is that.

**Comment by mrgwilliam** [comment]
Removed Launcher attachments, made attachments multiselection allowing for multiple selections.
